plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'net.aisw.wit'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	// https://mvnrepository.com/artifact/org.mybatis.spring.boot/mybatis-spring-boot-starter
	implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.5")
	
	// https://mvnrepository.com/artifact/org.apache.tomcat/tomcat-jasper
	implementation("org.apache.tomcat:tomcat-jasper:11.0.9")
	
	// https://mvnrepository.com/artifact/jakarta.servlet.jsp.jstl/jakarta.servlet.jsp.jstl-api
	implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.2'
	runtimeOnly 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'

	// WebSocket 라이브러리
	// https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-websocket
	implementation("org.springframework.boot:spring-boot-starter-websocket:3.5.3")
	
	// 메시지 관련 라이브러리
	// https://mvnrepository.com/artifact/org.springframework/spring-messaging
	implementation("org.springframework:spring-messaging:7.0.0-M6")
	
	// json 데이터 처리 라이브러리
	// https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
	implementation("com.fasterxml.jackson.core:jackson-core:2.19.1")
	
	// json 데이터 바인딩 라이브러리	
	// https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
	implementation("com.fasterxml.jackson.core:jackson-databind:2.19.1")
}

tasks.named('test') {
	useJUnitPlatform()
}
